name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup zig
        uses: goto-bus-stop/setup-zig@v2
      
      - name: Build
        run: make CC="zig cc"
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: xcm
          path: xcm